server:
  port: 8043
  
# CONECCION A BASE DE DATOS
spring:
  datasource:
    #url: jdbc:postgresql://localhost:5433/GOTALENT
    url: jdbc:postgresql://10.35.2.184:5431/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
# Hibernate ddl auto (create, create-drop, validate, update)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
